
CREATE TABLE IF NOT EXISTS bikes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  make varchar(100) NOT NULL,
  model varchar(100) NOT NULL,
  year_from integer,
  year_to integer,
  status varchar(20) NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT bikes_year_range_valid CHECK (
    (year_from IS NULL OR year_from BETWEEN 1950 AND 2100) AND
    (year_to IS NULL OR year_to BETWEEN 1950 AND 2100) AND
    (year_from IS NULL OR year_to IS NULL OR year_from <= year_to)
  ),
  CONSTRAINT bikes_status_valid CHECK (status IN ('active','inactive'))
);

CREATE UNIQUE INDEX IF NOT EXISTS bikes_identity_key
  ON bikes (lower(make), lower(model), COALESCE(year_from, 0), COALESCE(year_to, 0));

CREATE INDEX IF NOT EXISTS bikes_make_model_idx ON bikes (make, model);

CREATE TABLE IF NOT EXISTS bike_compatibility (
  bike_id integer NOT NULL REFERENCES bikes(id) ON DELETE CASCADE,
  product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (bike_id, product_id)
);

CREATE INDEX IF NOT EXISTS bike_compatibility_product_idx
  ON bike_compatibility(product_id);

INSERT INTO bikes (make, model, year_from, year_to)
VALUES
  ('Bajaj', 'Pulsar 150', 2018, 2026),
  ('Hero', 'Splendor Plus', 2018, 2026),
  ('Honda', 'CB Shine', 2018, 2026),
  ('Honda', 'CB Hornet 160R', 2018, 2022),
  ('Suzuki', 'Gixxer 150', 2018, 2026),
  ('TVS', 'Apache RTR 160', 2018, 2026),
  ('Yamaha', 'FZ-S', 2018, 2026),
  ('Yamaha', 'R15', 2018, 2026)
ON CONFLICT DO NOTHING;
